// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnPTXOdThGRVRm53ZFFlPk18s74EGPYPU',
    appId: '1:845969255852:web:fd3e5cb3c1ee6ec8501e09',
    messagingSenderId: '845969255852',
    projectId: 'iot-flutter-46ee1',
    authDomain: 'iot-flutter-46ee1.firebaseapp.com',
    databaseURL: 'https://iot-flutter-46ee1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-flutter-46ee1.appspot.com',
    measurementId: 'G-E267XM26VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5gRry-1AeT6_l9FaeEjczOjgkaWEXkl4',
    appId: '1:845969255852:android:5bbbc3c675c9eb66501e09',
    messagingSenderId: '845969255852',
    projectId: 'iot-flutter-46ee1',
    databaseURL: 'https://iot-flutter-46ee1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-flutter-46ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HpE9XJDu83NT5p8TSb1k681W7GpHD64',
    appId: '1:845969255852:ios:d47c46e3c46bbef4501e09',
    messagingSenderId: '845969255852',
    projectId: 'iot-flutter-46ee1',
    databaseURL: 'https://iot-flutter-46ee1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-flutter-46ee1.appspot.com',
    iosClientId: '845969255852-q94759j1d8frkbh2tk8na866lffht55n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0HpE9XJDu83NT5p8TSb1k681W7GpHD64',
    appId: '1:845969255852:ios:d47c46e3c46bbef4501e09',
    messagingSenderId: '845969255852',
    projectId: 'iot-flutter-46ee1',
    databaseURL: 'https://iot-flutter-46ee1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-flutter-46ee1.appspot.com',
    iosClientId: '845969255852-q94759j1d8frkbh2tk8na866lffht55n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
